const app=document.querySelector('#app');
const variants={carta:{theme:'letter',brand:'Un mensaje de Gonzalo',pre:'Para mis personas favoritas',title:'Tengo un secreto.<br>Y ya no me cabe dentro.',intro:'Hay cosas bonitas que solo tienen sentido cuando las compartes con los que más quieres.',button:'Abrir mi mensaje',label:'La familia crece',ending:'Mamá y papá vuelven a ser papás.<br>Y yo tengo el mejor papel de todos.',caption:'Gonzalo, hermano mayor'},cine:{theme:'malaga',brand:'<div class="radio-lockup"><b class="radio-small">RADIO</b><b class="radio-name">MARCA</b><b class="radio-city">MÁLAGA</b></div><div class="radio-tagline">LA ACTUALIDAD DEL DEPORTE MALAGUEÑO</div>',pre:'Exclusiva / Mercado de fichajes',title:'Un nuevo fichaje<br>para el <em>Málaga CF.</em>',intro:'El fichaje más especial no se explica con cifras. Se presenta con una imagen. Descubre al protagonista de esta historia.',button:'Descubrir el fichaje',label:'El verdadero notición está en casa',ending:'El fichaje no era para el Málaga…<br><strong>¡Es para nuestra familia!</strong><br>Volvemos a ser papás y Gonzalo asciende a hermano mayor.<br><br>Un nuevo miembro del equipo viene en camino.',caption:'Gonzalo · Capitán y futuro hermano mayor'},noticia:{theme:'news',brand:'La edición de Gonzalo',pre:'Tenemos una exclusiva',title:'Esta noticia<br>merece un titular.',intro:'He preparado algo para ti. Es cortito, pero te va a sacar una sonrisa.',button:'Descubrir la noticia',label:'Extra, extra · La familia crece',ending:'Confirmado: mamá y papá repiten.<br>Y yo asciendo a hermano mayor.',caption:'Gonzalo · Nuestro gran protagonista'}};
const key=new URLSearchParams(location.search).get('idea') || 'cine';
const item=variants[key];
if(!item){app.innerHTML=`<div class="gallery"><div class="eyebrow">Gonzalo tiene algo que contar</div><h1>Una pequeña web.<br>Una noticia enorme.</h1><p class="intro">Tres maneras de guardar el secreto unos segundos… y convertir una foto en un recuerdo para siempre.</p><div class="cards"><article class="card"><div class="sample letter"><small>01 / LA CARTA</small><b>Hay secretos<br>que abrazan.</b></div><div class="card-copy"><h2>Un mensaje muy suyo</h2><p>Íntima y emotiva. Un mensaje personal se abre para revelar su foto y la gran noticia.</p><a href="?idea=carta">Abrir la carta</a></div></article><article class="card"><div class="sample cinema"><small>02 / EL FICHAJE</small><b>Exclusiva<br>blanquiazul.</b></div><div class="card-copy"><h2>El fichaje más especial</h2><p>Una portada deportiva, un fichaje inesperado y Gonzalo con la noticia más importante.</p><a href="?idea=cine">Descubrir el fichaje</a></div></article><article class="card"><div class="sample news"><small>03 / LA EXCLUSIVA</small><b>¡Extra,<br>extra!</b></div><div class="card-copy"><h2>La noticia del año</h2><p>Amarillo vivo y un titular inolvidable. La propuesta más alegre y desenfadada.</p><a href="?idea=noticia">Leer la exclusiva</a></div></article></div><section class="notes"><h2>El mensaje antes de la sorpresa</h2><p>Envía el enlace de la propuesta elegida, no el de esta galería.</p><blockquote>💌 Gonzalo os ha preparado un mensajito. Abridlo juntos cuando tengáis un momento ❤️ [enlace de la carta]</blockquote><blockquote>👀 Ojo a este fichaje del Málaga… Abrid la noticia y dadle a «Descubrir el fichaje» 💙🤍 [enlace]</blockquote><blockquote>🗞️ Tenemos una exclusiva de Gonzalo que os va a sacar una sonrisa. Mejor verla hasta el final 😉 [enlace de la noticia]</blockquote><p>Mi favorita para la familia: <strong>la carta</strong>. Para sorprender con humor: <strong>la exclusiva</strong>.</p><p>La foto de Gonzalo ya está incluida en las tres propuestas, completa y sin recortar.</p></section></div>`;}else{
app.innerHTML=`<div class="experience ${item.theme}"><div class="brand eyebrow">${item.brand}</div>${key === 'cine' ? '<div class="club-strip"><img src="assets/malaga-cf.png" alt="Escudo del Málaga CF" width="64" height="64"><div><strong>MÁLAGA CF</strong><span>FÚTBOL / MERCADO DE FICHAJES</span></div></div>' : ''}<section class="gate"><div class="eyebrow">${item.pre}</div><h1>${item.title}</h1><p>${item.intro}</p><button id="open">${item.button}</button>${key === 'cine' ? '<div class="sports-meta"><span>MÁLAGA CF</span><span>LA HISTORIA COMPLETA</span></div>' : '<span class="signature">Con cariño, Gonzalo</span>'}</section><section class="reveal" hidden aria-label="El mensaje de Gonzalo"><div class="eyebrow">${item.label}</div><h1 tabindex="-1">¡Voy a ser<br><em>hermano mayor!</em></h1><figure class="photo"><img hidden draggable="false" alt="Gonzalo, el futuro hermano mayor"><div class="placeholder"><b>G</b><span>Aquí irá la foto de Gonzalo</span></div><figcaption>${item.caption}</figcaption></figure><p class="closing">${item.ending}</p>${key === 'cine' ? '<p class="family-note">Una sorpresa familiar hecha con cariño. Esta noticia es ficticia y no está vinculada a Radio Marca Málaga ni al Málaga CF.</p>' : ''}<button class="replay">Volver a abrir el mensaje</button></section></div>`;
const frame=app.querySelector('.photo');
// Barreras disuasorias; no impiden capturas ni acceso directo al archivo.
for(const event of ['contextmenu','dragstart']) frame.addEventListener(event,e=>e.preventDefault());
const photo=app.querySelector('.photo img');photo.addEventListener('load',()=>{photo.hidden=false;app.querySelector('.placeholder').hidden=true;});photo.src='assets/gonzalo.jpg';
const gate=app.querySelector('.gate'),reveal=app.querySelector('.reveal');
app.querySelector('#open').addEventListener('click',()=>{gate.hidden=true;reveal.hidden=false;reveal.querySelector('h1').focus({preventScroll:true});window.scrollTo(0,0);if(!matchMedia('(prefers-reduced-motion: reduce)').matches){for(let i=0;i<40;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=['#0087ce','#e8b938','#ffffff','#80c9eb'][i%4];c.style.animationDelay=Math.random()*.6+'s';document.body.append(c);setTimeout(()=>c.remove(),3600);}}});
app.querySelector('.replay').addEventListener('click',()=>{reveal.hidden=true;gate.hidden=false;app.querySelector('#open').focus();});}


